### ISSUE TITLE
'cf-abacus-dbserver' is not in the npm registry

### ISSUE THREAD

**Issue by balexander123** [jsdelfino/cf-abacus#5]
Trying to install abacus using the readme instructions.

Failed after 'npm run cfpush'

$ cat /Users/ba25714/Development/bluemix_sandbox/cf-abacus/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'owner',
1 verbose cli   'ls',
1 verbose cli   'cf-abacus-dbserver' ]
2 info using npm@2.7.5
3 info using node@v0.12.2
4 verbose node symlink /usr/local/bin/node
5 silly mapToRegistry name cf-abacus-dbserver
6 silly mapToRegistry using default registry
7 silly mapToRegistry registry https://registry.npmjs.org/
8 silly mapToRegistry uri https://registry.npmjs.org/cf-abacus-dbserver
9 verbose request uri https://registry.npmjs.org/cf-abacus-dbserver
10 verbose request no auth needed
11 info attempt registry request try #1 at 22:01:25
12 verbose request id 8a4afe2bcbbdc0f3
13 http request GET https://registry.npmjs.org/cf-abacus-dbserver
14 http 404 https://registry.npmjs.org/cf-abacus-dbserver
15 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
15 verbose headers   'content-type': 'application/json',
15 verbose headers   'cache-control': 'max-age=0',
15 verbose headers   'content-length': '51',
15 verbose headers   'accept-ranges': 'bytes',
15 verbose headers   date: 'Sat, 25 Jul 2015 05:01:13 GMT',
15 verbose headers   via: '1.1 varnish',
15 verbose headers   age: '0',
15 verbose headers   connection: 'keep-alive',
15 verbose headers   'x-served-by': 'cache-sjc3124-SJC',
15 verbose headers   'x-cache': 'MISS',
15 verbose headers   'x-cache-hits': '0',
15 verbose headers   'x-timer': 'S1437800473.309144,VS0,VE89' }
16 silly get cb [ 404,
16 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
16 silly get     'content-type': 'application/json',
16 silly get     'cache-control': 'max-age=0',
16 silly get     'content-length': '51',
16 silly get     'accept-ranges': 'bytes',
16 silly get     date: 'Sat, 25 Jul 2015 05:01:13 GMT',
16 silly get     via: '1.1 varnish',
16 silly get     age: '0',
16 silly get     connection: 'keep-alive',
16 silly get     'x-served-by': 'cache-sjc3124-SJC',
16 silly get     'x-cache': 'MISS',
16 silly get     'x-cache-hits': '0',
16 silly get     'x-timer': 'S1437800473.309144,VS0,VE89' } ]
17 error owner ls Couldn't get owner data cf-abacus-dbserver
18 verbose stack Error: 404 Not Found: cf-abacus-dbserver
18 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:245:14)
18 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
18 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:360:22)
18 verbose stack     at Request.emit (events.js:110:17)
18 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1202:14)
18 verbose stack     at Request.emit (events.js:129:20)
18 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1150:12)
18 verbose stack     at IncomingMessage.emit (events.js:129:20)
18 verbose stack     at _stream_readable.js:908:16
18 verbose stack     at process._tickCallback (node.js:355:11)
19 verbose statusCode 404
20 verbose pkgid cf-abacus-dbserver
21 verbose cwd /Users/ba25714/Development/bluemix_sandbox/cf-abacus
22 error Darwin 14.3.0
23 error argv "node" "/usr/local/bin/npm" "owner" "ls" "cf-abacus-dbserver"
24 error node v0.12.2
25 error npm  v2.7.5
26 error code E404
27 error 404 Not Found: cf-abacus-dbserver
27 error 404
27 error 404 'cf-abacus-dbserver' is not in the npm registry.
27 error 404 You should bug the author to publish it (or use the name yourself!)
27 error 404
27 error 404 Note that you can also install from a
27 error 404 tarball, folder, http url, or git url.
28 verbose exit [ 1, true ]

**Comment by jsdelfino** [comment]
I'm planning to push the Abacus modules to the npm registry sometime next week. In the meantime, the push to CF should still work with the following steps:

```
# install all the node dependencies as well as the dependencies on Abacus local modules
# which are not in the npm registry yet
npm install

# push to CF
npm run cfpush
```

These two steps are described in the README but in separate sections, so I just committed 4dce896 to add that npm install step to the 'Deploying to Cloud Foundry' section as well.

Does a local npm install before npm run cfpush fix the issue for you?

**Comment by balexander123** [comment]
I did do npm install before the cfpush, no it does not fix the issue.  i can see the cf-abacus modules including cf-abacus-dbserver.  

$ npm list | grep cf-abacus-dbserver
├─┬ cf-abacus-dbserver@0.0.1

$ npm run cfpush

> cf-abacus@0.0.1 cfpush /Users/ba25714/Development/bluemix_sandbox/cf-abacus
> bin/cfpush

+ cd lib/utils/dbserver
+ npm run cfpush

> cf-abacus-dbserver@0.0.1 cfpush /Users/ba25714/Development/bluemix_sandbox/cf-abacus/lib/utils/dbserver
> ../../../tools/packapp/packapp && cf push

FAILED
Error reading manifest file:
Expected environment variable NODE_MODULES_CACHE to have a string value, but it was a bool.

**Comment by jsdelfino** [comment]
Looks like the push is going further this time and failing with a new error in the CF CLI:
> Expected environment variable NODE_MODULES_CACHE to have a string value, but it was a bool.

caused by this line in the Abacus CF app manifests:
```
NODE_MODULES_CACHE: true
```

What version of the CF CLI (cf --version) are you using?

Does changing lib/utils/dbserver/manifest.yml to NODE_MODULES: "true" help?

**Comment by balexander123** [comment]
```bash
$ cf --version
cf version 6.1.1-homebrew
$ cat lib/utils/dbserver/manifest.yml
applications:
- name: cf-abacus-dbserver
  host: cf-abacus-dbserver
  path: app.zip
  instances: 1
  memory: 1G
  disk_quota: 1G
  env:
    NODE_MODULES_CACHE: "true"
```

I had to edit the following with the same change:
lib/stubs/account/manifest.yml
lib/stubs/provisioning/manifest.yml
lib/metering/collector/manifest.yml

Was able to get everything deployed after making those edits.  The cf-abacus apps all started but had this health check failure:

```bash
-----> Uploading droplet (34M)

0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
1 of 1 instances running

App started

Showing health and status for app cf-abacus-dbserver in org GAP / space dev as ...
FAILED
Error performing request: Get https://api.sr1.us-south.bluemix.net/v2/apps/42e8499a-6cf4-48d6-9132-352e694dacd9/summary: EOF
```

**Comment by jsdelfino** [comment]
> I had to edit the following with the same change:
> lib/stubs/account/manifest.yml
> lib/stubs/provisioning/manifest.yml
> lib/metering/collector/manifest.yml

I'm also thinking about removing that NODE_MODULES_CACHE altogether anyway. It helped at some point when we were debugging and wanted to make sure that no older version of a module from that cache would get in the way, but it's probably not needed anymore, at least not in the default manifest.yml for those apps.

I also noticed that you set it to "true" which I believe is the default value, so removing it wouldn't hurt. I'll try to push that change today.

About that error:
```
Showing health and status for app cf-abacus-dbserver in org GAP / space dev as ...
FAILED
Error performing request: Get https://api.sr1.us-south.bluemix.net/v2/apps/42e8499a-6cf4-48d6-9132-352e694dacd9/summary: EOF
```

Do you have enough memory in your Bluemix account (I believe the default is 2GB) to deploy all those apps?

What does cf logs (or cf-logs --recent after the fact) show you for that app?

**Comment by balexander123** [comment]
I believe all the abacus apps are starting ok now.

```bash
$ cf apps |grep cf-abacus
cf-abacus-usage-reporting     started           2/2         512M     1G     cf-abacus-usage-reporting.sr1.us-south.mybluemix.net   
cf-abacus-usage-meter         started           2/2         512M     1G     cf-abacus-usage-meter.sr1.us-south.mybluemix.net   
cf-abacus-usage-collector     started           2/2         512M     1G     cf-abacus-usage-collector.sr1.us-south.mybluemix.net   
cf-abacus-account-stub        started           2/2         512M     1G     cf-abacus-account-stub.sr1.us-south.mybluemix.net   
cf-abacus-usage-aggregator    started           4/4         512M     1G     cf-abacus-usage-aggregator.sr1.us-south.mybluemix.net   
cf-abacus-usage-accumulator   started           4/4         512M     1G     cf-abacus-usage-accumulator.sr1.us-south.mybluemix.net   
cf-abacus-dbserver            started           1/1         1G       1G     cf-abacus-dbserver.sr1.us-south.mybluemix.net   
cf-abacus-provisioning-stub   started           2/2         512M     1G     cf-abacus-provisioning-stub.sr1.us-south.mybluemix.net
```

**Comment by jsdelfino** [comment]
The modules are now in the npm registry, so that should make them easier to use.
See [abacus-dbserver](https://www.npmjs.com/package/abacus-dbserver) for example.
